# Site settings
title:          荒岛书生
description:    "程序员，流行音乐、古琴、网络文学与传统文学爱好者。"
baseurl:        ""
url:            "https://www.lidaxiang.cn/index/"

# Author
author:
  name:         荒岛书生
  url:          https://www.lidaxiang.cn/index/
  email:        0lidaxiang@gmail.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-paginate
  - jekyll-sitemap

# Permalinks
permalink:      /:year-:month-:day/:title

# 首页显示的文章分页，每页数量
paginate:       20

# 文章摘要标识符
excerpt_separator: '<!---more--->'

# 目录结构
# source:      .
# destination: ./_site
# plugins:     ./_plugins
# layouts:     ./_layouts
# data_source: ./_data
# collections: null
# sitemap: True

# categories:
#   - sssss
#   - wowww
